export const NORMALIZER = "NORMALIZER";
export const PRE_LEMMATIZER = "PRE_LEMMATIZER";
export const LEMMATIZER = "LEMMATIZER";
export const DUPLICATE_CHECKER = "DUPLICATE_CHECKER";
export const DEFINITION_PROVIDER = "DEFINITION_PROVIDER";
export const GAP_FILL_SERVICE = "GAP_FILL_SERVICE";
export const CARD_ASSEMBLER = "CARD_ASSEMBLER";
